- id: '1587313233798'
  name: Fin de film le soir
  entities:
    light.lumiere_salon_light:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      off_with_transition: false
      off_brightness:
      friendly_name: Lumière salon Light
      supported_features: 40
      color_mode: color_temp
      brightness: 80
      color_temp_kelvin: 3787
      color_temp: 264
      hs_color:
      - 26.933
      - 38.871
      rgb_color:
      - 255
      - 200
      - 155
      xy_color:
      - 0.434
      - 0.369
      state: 'on'
    light.arbre_violet:
      supported_color_modes:
      - onoff
      friendly_name: Arbre violet
      supported_features: 0
      color_mode: onoff
      state: 'on'
    light.derriere_tele:
      supported_color_modes:
      - onoff
      friendly_name: Derrière TV
      supported_features: 0
      color_mode: onoff
      state: 'on'
  metadata:
    light.arbre_violet:
      entity_only: true
    light.derriere_tele:
      entity_only: true
- id: '1608299040375'
  name: Eclairages Noel
  entities:
    light.arbre_violet:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: arbre violet
      supported_features: 0
      state: 'on'
    light.derriere_tele:
      supported_color_modes:
      - onoff
      friendly_name: derrière télé
      supported_features: 0
      state: 'off'
    light.sapin_de_noel:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: Sapin de Noël
      supported_features: 0
      state: 'on'
    light.wled:
      effect_list:
      - Android
      - Aurora
      - Blends
      - Blink
      - Blink Rainbow
      - Bouncing Balls
      - Bpm
      - Breathe
      - Candle
      - Candle Multi
      - Candy Cane
      - Chase
      - Chase 2
      - Chase 3
      - Chase Flash
      - Chase Flash Rnd
      - Chase Rainbow
      - Chase Random
      - Chunchun
      - Colorful
      - Colorloop
      - Colortwinkles
      - Colorwaves
      - Dancing Shadows
      - Dissolve
      - Dissolve Rnd
      - Drip
      - Dynamic
      - Dynamic Smooth
      - Fade
      - Fairy
      - Fairytwinkle
      - Fill Noise
      - Fire 2012
      - Fire Flicker
      - Fireworks
      - Fireworks 1D
      - Fireworks Starburst
      - Flow
      - Glitter
      - Gradient
      - Halloween
      - Halloween Eyes
      - Heartbeat
      - ICU
      - Juggle
      - Lake
      - Lighthouse
      - Lightning
      - Loading
      - Meteor
      - Meteor Smooth
      - Multi Comet
      - Noise 1
      - Noise 2
      - Noise 3
      - Noise 4
      - Noise Pal
      - Oscillate
      - Pacifica
      - Palette
      - Percent
      - Phased
      - Phased Noise
      - Plasma
      - Police
      - Popcorn
      - Pride 2015
      - Railway
      - Rain
      - Rainbow
      - Rainbow Runner
      - Random Colors
      - Ripple
      - Ripple Rainbow
      - Running
      - Running Dual
      - Saw
      - Scan
      - Scan Dual
      - Scanner
      - Scanner Dual
      - Sine
      - Sinelon
      - Sinelon Dual
      - Sinelon Rainbow
      - Solid
      - Solid Glitter
      - Solid Pattern
      - Solid Pattern Tri
      - Sparkle
      - Sparkle Dark
      - Sparkle+
      - Spots
      - Spots Fade
      - Stream
      - Stream 2
      - Strobe
      - Strobe Mega
      - Strobe Rainbow
      - Sunrise
      - Sweep
      - Sweep Random
      - TV Simulator
      - Tetrix
      - Theater
      - Theater Rainbow
      - Traffic Light
      - Tri Fade
      - Tri Wipe
      - Twinkle
      - Twinklecat
      - Twinklefox
      - Twinkleup
      - Two Dots
      - Washing Machine
      - Wipe
      - Wipe Random
      supported_color_modes:
      - rgb
      color_mode: rgb
      brightness: 164
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      effect: Sunrise
      icon: mdi:led-strip-variant
      friendly_name: WLED
      supported_features: 36
      state: 'on'
    light.sapin_de_noel:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: sapin de Noel
      supported_features: 0
      state: 'on'
    light.eclairage_exterieur_entree_light:
      supported_color_modes:
      - onoff
      color_mode: onoff
      off_brightness:
      friendly_name: Interrupteur guirlande extérieure on_off
      supported_features: 8
      state: 'on'
    light.decorations_de_noel:
      effect_list:
      - Android
      - Aurora
      - Blends
      - Blink
      - Blink Rainbow
      - Bouncing Balls
      - Bpm
      - Breathe
      - Candle
      - Candle Multi
      - Candy Cane
      - Chase
      - Chase 2
      - Chase 3
      - Chase Flash
      - Chase Flash Rnd
      - Chase Rainbow
      - Chase Random
      - Chunchun
      - Colorful
      - Colorloop
      - Colortwinkles
      - Colorwaves
      - Dancing Shadows
      - Dissolve
      - Dissolve Rnd
      - Drip
      - Dynamic
      - Dynamic Smooth
      - Fade
      - Fairy
      - Fairytwinkle
      - Fill Noise
      - Fire 2012
      - Fire Flicker
      - Fireworks
      - Fireworks 1D
      - Fireworks Starburst
      - Flow
      - Glitter
      - Gradient
      - Halloween
      - Halloween Eyes
      - Heartbeat
      - ICU
      - Juggle
      - Lake
      - Lighthouse
      - Lightning
      - Loading
      - Meteor
      - Meteor Smooth
      - Multi Comet
      - Noise 1
      - Noise 2
      - Noise 3
      - Noise 4
      - Noise Pal
      - Oscillate
      - Pacifica
      - Palette
      - Percent
      - Phased
      - Phased Noise
      - Plasma
      - Police
      - Popcorn
      - Pride 2015
      - Railway
      - Rain
      - Rainbow
      - Rainbow Runner
      - Random Colors
      - Ripple
      - Ripple Rainbow
      - Running
      - Running Dual
      - Saw
      - Scan
      - Scan Dual
      - Scanner
      - Scanner Dual
      - Sine
      - Sinelon
      - Sinelon Dual
      - Sinelon Rainbow
      - Solid
      - Solid Glitter
      - Solid Pattern
      - Solid Pattern Tri
      - Sparkle
      - Sparkle Dark
      - Sparkle+
      - Spots
      - Spots Fade
      - Stream
      - Stream 2
      - Strobe
      - Strobe Mega
      - Strobe Rainbow
      - Sunrise
      - Sweep
      - Sweep Random
      - TV Simulator
      - Tetrix
      - Theater
      - Theater Rainbow
      - Traffic Light
      - Tri Fade
      - Tri Wipe
      - Twinkle
      - Twinklecat
      - Twinklefox
      - Twinkleup
      - Two Dots
      - Washing Machine
      - Wipe
      - Wipe Random
      supported_color_modes:
      - brightness
      - onoff
      - rgb
      color_mode: rgb
      brightness: 209
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      effect: Sunrise
      entity_id:
      - light.sapin_de_noel
      - light.wled
      icon: mdi:lightbulb-group
      friendly_name: Décorations de Noël
      supported_features: 36
      state: 'on'
  icon: mdi:mdi-pine-tree
- id: '1609358906803'
  name: pré minuit nouvel an
  entities:
    light.derriere_tele:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: derrière télé
      supported_features: 0
      state: 'on'
    light.sapin_de_noel:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: sapin de Noel
      supported_features: 0
      state: 'on'
    light.wled:
      state: 'on'
    select.wled_preset:
      icon: mdi:playlist-play
      friendly_name: WLED Preset
      state: Pre minuit
- id: '1609359058615'
  name: minuit nouvel an
  entities:
    light.derriere_tele:
      state: 'on'
    light.sapin_de_noel:
      state: 'on'
    light.wled:
      state: 'on'
    select.wled_preset:
      state: Minuit
